# Generated by Django 3.2 on 2021-08-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictApp', '0002_auto_20210813_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('Instructor_ID', models.CharField(max_length=20)),
                ('Instructor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_instructor',
        ),
        migrations.AddField(
            model_name='subject_refer',
            name='subject_instructor_ID',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
