# Generated by Django 3.2 on 2021-09-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictApp', '0004_subject_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_menu',
            name='id',
        ),
        migrations.AddField(
            model_name='subject_menu',
            name='menu_id',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject_menu',
            name='order',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
