# Generated by Django 3.2 on 2021-09-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictApp', '0005_auto_20210911_0224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject_menu',
        ),
    ]
