# Generated by Django 3.2 on 2021-09-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictApp', '0007_menu_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_subject',
            name='menu_id',
            field=models.CharField(max_length=4),
        ),
    ]
