# Generated by Django 3.2 on 2021-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictApp', '0009_alter_menu_subject_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_subject',
            name='img_menu',
            field=models.CharField(default=1, max_length=124),
            preserve_default=False,
        ),
    ]
