# Generated by Django 3.2 on 2021-09-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictApp', '0011_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='criterion',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('upper', models.IntegerField()),
                ('lower', models.IntegerField()),
                ('text', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='end_CharField',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='start_CharField',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menu_subject',
            name='menu_id',
            field=models.IntegerField(),
        ),
    ]
