# Generated by Django 3.2 on 2021-09-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictApp', '0012_auto_20210919_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='text_color',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criterion',
            name='text',
            field=models.CharField(max_length=124),
        ),
    ]
